# ==========================================
# 💖 CONFIGURACIÓN DE PATROCINIO - CHOCÓ FACTORY
# ==========================================

# GitHub Sponsors: Tu perfil oficial aprobado
github: [choco-latito29]

# PayPal: Al usar el link directo, GitHub mostrará el icono automáticamente
custom:
